function [content_text,N_figures,N_Table,N_equation,N_refer]= Title2_1_Paragraph2(N_figures,N_Table,N_equation,N_refer)
content_text=strcat(['where S is the concentration of SO_4^{2-} in the test solution (mg/l), t is the corrosive period (days)' ...
    ' and C3A is the percentage of tricalcium aluminate in the Portland cement calculated from Bogue’s equations. ' ...
    'To account for the effect of supplementary cementing materials, the Eq. (1) is multiplied by a correcting term \eta_a:']);