function [content_text,N_figures,N_Table,N_equation,N_refer]= Title2_2_Paragraph1(N_figures,N_Table,N_equation,N_refer)
content_text=strcat(['Based on a degradation data of concrete fully immersed in ' ...
    'a 0.19 M for five-year period obtained from Harrison and Teychenne [ ], the ' ...
    'location (Xs) of the visible degradation zone within corrosive concrete is' ...
    ' proposed by Atkinson and Hearne [ ]:']);