function [content_text,N_figures,N_Table,N_equation,N_refer]= Title2_1_Paragraph1(N_figures,N_Table,N_equation,N_refer)
content_text=strcat('Jambor [',num2str(N_refer) ,'] developed an empirical equation to describe the rate of corrosion of cement-based materials ', ...
    ' subjected to sulfate attack. According to the experimental data over a fifteen-year period of corrosion, a', ...
    ' degree of corrosion induced by sulfate attack is proposed:');