function [content_text,N_figures,N_Table,N_equation,N_refer]= Title2_1_Paragraph3(N_figures,N_Table,N_equation,N_refer)
content_text=strcat(['where A represents the percentage of supplementary cementing material ' ...
    'in the total mass of binder. Eq. (1) and Eq. (2) were reported to be valid for mortar with' ...
    ' a ratio of water to binder of 0.6 and full immersion in sodium sulfate solution [18]. ' ...
    'These equations do not consider any variations in the test conditions. Therefore, ' ...
    'they are powerless in predicting or designing the durability of cement-based materials ' ...
    'exposed to salt solutions with sulfate ions.']);